### PR TITLE
fix(apple): Rewind files after fetching from objectstore

### LINKED ISSUE #1884: Uploading iOS crash reports with send-envelope no longer works
### CLI Version

3.2.1

### Operating System and Architecture

- [x] macOS (arm64)
- [ ] macOS (x86_64)
- [ ] Linux (i686)
- [ ] Linux (x86_64)
- [ ] Linux (armv7)
- [ ] Linux (aarch64)
- [ ] Windows (i686)
- [ ] Windows (x86_64)

### Operating System Version

macOS Sequoia 15.7.2

### Link to reproduction repository

_No response_

### CLI Command

sentry-cli send-envelope /path/to/envelope-file

### Exact Reproduction Steps

 - Create a valid envelop from an iOS crash report (documentation [here](https://develop.sentry.dev/sdk/foundations/data-model/envelopes/)).
 - Upload it to Sentry with the command line tool: sentry-cli send-envelope /path/to/envelope-file

Typically, the payload of an envelope looks like this:
```
{"event_id":"<event-id>"}
{"type":"event","length":<event-size>}
{"level":"fatal","platform":"cocoa","environment":"<environment>","release":"<release>"}
{"type":"attachment","attachment_type":"event.applecrashreport","content_type":"text/plain","length":<attachement-size>}
<crash-report>
```
The values in `<>` must be properly replaced.

### Expected Results

The symbolicated crash report appears in Sentry's web interface.

### Actual Results

Although the command itself still works and exits successfully (after printing `/path/to/envelope-file dispatched`), the backend processing of the crash report fails. In the web interface, it says "Invalid Apple Crash Report" although the crash report is valid.

There are 3 possible formats for crash reports (none of them work):
 - The historical textual format (.crash files). This is what Xcode Organizer provides when doing right click, show in Finder.
 - The JSON format (.ips files, not actually JSON because it's 2 JSON concatenated together). This is what can be extracted from a device or what Apple attaches to App Store rejections.
 - The "full report" (concatenation of the textual format and the JSON format). This is what the Console app shows when opening an ips file.

Examples:
 - https://amoamoamo.sentry.io/organizations/amoamoamo/issues/7282823812 (when using textual format or full report)
 - https://amoamoamo.sentry.io/organizations/amoamoamo/issues/7282894559 (when using JSON format)

Image

### Logs

n/a

### PR DESCRIPTION
**Pull request by jjbayer**
Downloads from objectstore did not rewind the `File` object after downloading, leading to seemingly empty crash reports. This did not cause an issue for minidumps because they are mapped as `ByteView`.

Follow-up: Use the existing download service (https://github.com/getsentry/symbolicator/pull/1928).

Fixes https://github.com/getsentry/symbolicator/issues/1884.

### CODE REVIEW

File: crates/symbolicator-native/tests/integration/process_apple.rs [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+use axum::routing::get;
+use symbolicator_test::Server;
+
+use symbolicator_native::interface::AttachmentFile;
+use symbolicator_service::types::Scope;
+
+use crate::{assert_snapshot, read_fixture, setup_service, symbol_server};
+
+#[tokio::test]
+async fn test_attachment_download() {
```
Comment (jjbayer) [inline crates/symbolicator-native/tests/integration/process_apple.rs:15]: There's a similar test in `process_minidump.rs`, but apple crash report downloads had no test coverage.

Without the fix in `attachments.rs`, this test fails with the same empty stack trace as we saw in #1884.

File: crates/symbolicator-native/src/symbolication/attachments.rs [hunk 2]
```diff
@@ -20,29 +19,20 @@ pub async fn download_attachment(
         } => (storage_url, storage_token),
     };
 
-    // TODO: maybe its worth using the actual `DownloadService` instead of straight going to the `trusted_client`.
-    // Doing so would in theory allow us to have retries and error report, as well as being able to
-    // download files in multiple chunks concurrently, but I don’t think our `objecstore` server currently
-    // supports range requests, and those would also mess with streaming decompression.
-    // Not to mention that using the `DownloadService` is not that straight forward.
-    let mut request = download_svc.trusted_client.get(storage_url);
+    let mut http_remote_file = HttpRemoteFile::from_url(Url::parse(&storage_url)?, true);
```
Comment (loewenheim) [inline crates/symbolicator-native/src/symbolication/attachments.rs]: Possible refinement: Replace `AttachmentFile::Remote {storage_url, storage_token}` with `AttachmentFile::Remote(HttpRemoteFile)` and already create the `HttpRemoteFile` in the endpoint.

File: crates/symbolicator-native/tests/integration/process_apple.rs [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+    let (symbolication, _cache_dir) = setup_service(|_| ());
+    let (_symsrv, source) = symbol_server();
+
+    async fn get_crash_report() -> impl IntoResponse {
+        let minidump = read_fixture("apple_crash_report.txt");
```
Comment (loewenheim) [inline crates/symbolicator-native/tests/integration/process_apple.rs]:
```suggestion
        let apple_crash_report = read_fixture("apple_crash_report.txt");
```

**Comment by jjbayer** [comment]
I split out the refactor to https://github.com/getsentry/symbolicator/pull/1928 because it failed sentry tests for minidumps.

**Review by loewenheim — APPROVED** [review]

**Comment by loewenheim** [comment]
This deserves a changelog entry.

**Review by Dav1dde — APPROVED** [review]
Test Coverage 🙏
