### PR TITLE
fix(bitcode): Do not error out for source errors

### LINKED ISSUE #640: Sentry download failures are not tolerated
### Environment

Self hosted sentry behind access enforcing proxy.

### Steps to Reproduce

Imagine that you only want to download debug info from Debian debuginfod. Your Sentry instance is not really accessible to symbolicator directly, which we can simulate with the following payload:

```json
{
  "sources": [
    {
      "type": "sentry",
      "id": "sentry:project",
      "url": "https://example.com/",
      "token": "4c187caea9f84a50a7cac392f1e38617"
    },
    {
      "id": "imu37nhqd4g",
      "url": "https://debuginfod.debian.net/buildid/",
      "name": "Debian debuginfod",
      "type": "http",
      "layout": {
        "casing": "default",
        "type": "debuginfod"
      }
    }
  ],
  "options": {
    "dif_candidates": true,
    "compare_stackwalking_methods": false
  },
  "stacktraces": [
    {
      "registers": {},
      "frames": [
        {
          "function": "__libc_start_main",
          "in_app": true,
          "instruction_addr": "0x7f999c1a8d0a"
        }
      ]
    }
  ],
  "modules": [
    {
      "code_id": "54eef5ce96cf37cb175b0d93186836ca1caf470c",
      "code_file": "/lib/x86_64-linux-gnu/libc.so.6",
      "debug_id": "cef5ee54-cf96-cb37-175b-0d93186836ca",
      "image_addr": "0x7f999c182000",
      "image_size": 1852680,
      "type": "symbolic"
    }
  ]
}
```

You can send it to symbolicator:

```
curl -s -X POST -H "Content-Type: application/json" 'http://localhost:3021/symbolicate?timeout=100&scope=554' -d @derp.json | jq .
```

### Expected Result

I expect to see symbols resolved from debuginfod, even though sentry is not available:

```json
{
  "status": "completed",
  "stacktraces": [
    {
      "frames": [
        {
          "status": "symbolicated",
          "original_index": 0,
          "instruction_addr": "0x7f999c1a8d0a",
          "package": "/lib/x86_64-linux-gnu/libc.so.6",
          "lang": "c",
          "symbol": "__libc_start_main",
          "sym_addr": "0x7f999c1a8c20",
          "function": "__libc_start_main",
          "filename": "../csu/libc-start.c",
          "abs_path": "csu/libc-start.c",
          "lineno": 308
        }
      ]
    }
  ],
  "modules": [
    {
      "debug_status": "found",
      "features": {
        "has_debug_info": true,
        "has_unwind_info": false,
        "has_symbols": true,
        "has_sources": false
      },
      "arch": "x86_64",
      "type": "unknown",
      "code_id": "54eef5ce96cf37cb175b0d93186836ca1caf470c",
      "code_file": "/lib/x86_64-linux-gnu/libc.so.6",
      "debug_id": "cef5ee54-cf96-cb37-175b-0d93186836ca",
      "image_addr": "0x7f999c182000",
      "image_size": 1852680,
      "candidates": [
        {
          "source": "imu37nhqd4g",
          "location": "https://debuginfod.debian.net/buildid/54eef5ce96cf37cb175b0d93186836ca1caf470c/debuginfo",
          "download": {
            "status": "ok",
            "features": {
              "has_debug_info": true,
              "has_unwind_info": false,
              "has_symbols": true,
              "has_sources": false
            }
          },
          "debug": {
            "status": "ok"
          }
        },
        {
          "source": "imu37nhqd4g",
          "location": "https://debuginfod.debian.net/buildid/54eef5ce96cf37cb175b0d93186836ca1caf470c/executable",
          "download": {
            "status": "notfound"
          }
        }
      ]
    }
  ]
}
```

This works if I remove sentry source from the payload.

### Actual Result

Sentry fails to be accessed, which prevents debuginfod from engaging as well:

```json
{
  "status": "completed",
  "stacktraces": [
    {
      "frames": [
        {
          "status": "missing",
          "original_index": 0,
          "instruction_addr": "0x7f999c1a8d0a",
          "package": "/lib/x86_64-linux-gnu/libc.so.6",
          "function": "__libc_start_main"
        }
      ]
    }
  ],
  "modules": [
    {
      "debug_status": "other",
      "features": {
        "has_debug_info": false,
        "has_unwind_info": false,
        "has_symbols": false,
        "has_sources": false
      },
      "arch": "unknown",
      "type": "unknown",
      "code_id": "54eef5ce96cf37cb175b0d93186836ca1caf470c",
      "code_file": "/lib/x86_64-linux-gnu/libc.so.6",
      "debug_id": "cef5ee54-cf96-cb37-175b-0d93186836ca",
      "image_addr": "0x7f999c182000",
      "image_size": 1852680
    }
  ]
}
```

Debug level logs:

```
 INFO  symbolicator::server > Starting server on 127.0.0.1:3021
 DEBUG symbolicator::services::download::sentry > Fetching list of Sentry debug files from https://example.com/?debug_id=cef5ee54-cf96-cb37-175b-0d93186836ca&file_formats=pdb&file_formats=macho&file_formats=elf&file_formats=pe&file_formats=macho&file_formats=elf&file_formats=wasm&file_formats=wasm&file_formats=breakpad&file_formats=sourcebundle&file_formats=uuidmap&file_formats=bcsymbolmap&code_id=54eef5ce96cf37cb175b0d93186836ca1caf470c
 DEBUG reqwest::connect                         > starting new connection: https://example.com/
 DEBUG trust_dns_proto::xfer::dns_handle        > querying: example.com A
 DEBUG trust_dns_resolver::name_server::name_server_pool > sending request: [Query { name: Name { is_fqdn: false, label_data: [101, 120, 97, 109, 112, 108, 101, 99, 111, 109], label_ends: [7, 10] }, query_type: A, query_class: IN }]
 DEBUG trust_dns_resolver::name_server::name_server      > reconnecting: NameServerConfig { socket_addr: 169.254.255.254:53, protocol: Udp, tls_dns_name: None, trust_nx_responses: false }
 DEBUG trust_dns_proto::xfer                             > enqueueing message: [Query { name: Name { is_fqdn: false, label_data: [101, 120, 97, 109, 112, 108, 101, 99, 111, 109], label_ends: [7, 10] }, query_type: A, query_class: IN }]
 DEBUG trust_dns_proto::udp::udp_stream                  > created socket successfully
 DEBUG trust_dns_proto::udp::udp_client_stream           > received message id: 49448
 DEBUG reqwest::async_impl::client                       > response '200 OK' for https://example.com/?debug_id=cef5ee54-cf96-cb37-175b-0d93186836ca&file_formats=pdb&file_formats=macho&file_formats=elf&file_formats=pe&file_formats=macho&file_formats=elf&file_formats=wasm&file_formats=wasm&file_formats=breakpad&file_formats=sourcebundle&file_formats=uuidmap&file_formats=bcsymbolmap&code_id=54eef5ce96cf37cb175b0d93186836ca1caf470c
 DEBUG reqwest::async_impl::client                       > response '200 OK' for https://example.com/?debug_id=cef5ee54-cf96-cb37-175b-0d93186836ca&file_formats=pdb&file_formats=macho&file_formats=elf&file_formats=pe&file_formats=macho&file_formats=elf&file_formats=wasm&file_formats=wasm&file_formats=breakpad&file_formats=sourcebundle&file_formats=uuidmap&file_formats=bcsymbolmap&code_id=54eef5ce96cf37cb175b0d93186836ca1caf470c
 DEBUG reqwest::async_impl::client                       > response '200 OK' for https://example.com/?debug_id=cef5ee54-cf96-cb37-175b-0d93186836ca&file_formats=pdb&file_formats=macho&file_formats=elf&file_formats=pe&file_formats=macho&file_formats=elf&file_formats=wasm&file_formats=wasm&file_formats=breakpad&file_formats=sourcebundle&file_formats=uuidmap&file_formats=bcsymbolmap&code_id=54eef5ce96cf37cb175b0d93186836ca1caf470c
 DEBUG reqwest::async_impl::client                       > response '200 OK' for https://example.com/?debug_id=cef5ee54-cf96-cb37-175b-0d93186836ca&file_formats=pdb&file_formats=macho&file_formats=elf&file_formats=pe&file_formats=macho&file_formats=elf&file_formats=wasm&file_formats=wasm&file_formats=breakpad&file_formats=sourcebundle&file_formats=uuidmap&file_formats=bcsymbolmap&code_id=54eef5ce96cf37cb175b0d93186836ca1caf470c
 ERROR symbolicator::services::objects                   > Failed to fetch file list from sentry: failed to fetch data from Sentry
  caused by: failed sending request to Sentry
  caused by: error decoding response body: expected value at line 1 column 1
  caused by: expected value at line 1 column 1
 DEBUG symbolicator::services::download::http            > Fetching debug file from https://debuginfod.debian.net/buildid/54eef5ce96cf37cb175b0d93186836ca1caf470c/debuginfo
 DEBUG symbolicator::services::download::http            > Fetching debug file from https://debuginfod.debian.net/buildid/54eef5ce96cf37cb175b0d93186836ca1caf470c/executable
 DEBUG reqwest::connect                                  > starting new connection: https://debuginfod.debian.net/
 DEBUG reqwest::connect                                  > starting new connection: https://debuginfod.debian.net/
 DEBUG trust_dns_proto::xfer::dns_handle                 > querying: debuginfod.debian.net A
 DEBUG trust_dns_resolver::name_server::name_server_pool > sending request: [Query { name: Name { is_fqdn: false, label_data: [100, 101, 98, 117, 103, 105, 110, 102, 111, 100, 100, 101, 98, 105, 97, 110, 110, 101, 116], label_ends: [10, 16, 19] }, query_type: A, query_class: IN }]
 DEBUG trust_dns_resolver::name_server::name_server      > reconnecting: NameServerConfig { socket_addr: 169.254.255.254:53, protocol: Udp, tls_dns_name: None, trust_nx_responses: false }
 DEBUG trust_dns_proto::xfer                             > enqueueing message: [Query { name: Name { is_fqdn: false, label_data: [100, 101, 98, 117, 103, 105, 110, 102, 111, 100, 100, 101, 98, 105, 97, 110, 110, 101, 116], label_ends: [10, 16, 19] }, query_type: A, query_class: IN }]
 DEBUG trust_dns_proto::xfer::dns_handle                 > querying: debuginfod.debian.net A
 DEBUG trust_dns_resolver::name_server::name_server_pool > sending request: [Query { name: Name { is_fqdn: false, label_data: [100, 101, 98, 117, 103, 105, 110, 102, 111, 100, 100, 101, 98, 105, 97, 110, 110, 101, 116], label_ends: [10, 16, 19] }, query_type: A, query_class: IN }]
 DEBUG trust_dns_resolver::name_server::name_server      > existing connection: NameServerConfig { socket_addr: 169.254.255.254:53, protocol: Udp, tls_dns_name: None, trust_nx_responses: false }
 DEBUG trust_dns_proto::xfer                             > enqueueing message: [Query { name: Name { is_fqdn: false, label_data: [100, 101, 98, 117, 103, 105, 110, 102, 111, 100, 100, 101, 98, 105, 97, 110, 110, 101, 116], label_ends: [10, 16, 19] }, query_type: A, query_class: IN }]
 DEBUG trust_dns_proto::udp::udp_stream                  > created socket successfully
 DEBUG trust_dns_proto::udp::udp_stream                  > created socket successfully
 DEBUG trust_dns_proto::udp::udp_client_stream           > received message id: 63394
 DEBUG trust_dns_proto::udp::udp_client_stream           > received message id: 53222
 DEBUG reqwest::async_impl::client                       > response '200 OK' for https://debuginfod.debian.net/buildid/54eef5ce96cf37cb175b0d93186836ca1caf470c/debuginfo
 DEBUG reqwest::async_impl::client                       > response '404 Not Found' for https://debuginfod.debian.net/buildid/54eef5ce96cf37cb175b0d93186836ca1caf470c/executable
 DEBUG symbolicator::services::download::http            > Unexpected client error status code from https://debuginfod.debian.net/buildid/54eef5ce96cf37cb175b0d93186836ca1caf470c/executable: 404 Not Found
 DEBUG symbolicator::services::download                  > Debug file not found at HTTP source 'imu37nhqd4g' location '54eef5ce96cf37cb175b0d93186836ca1caf470c/executable'
 DEBUG symbolicator::services::objects::data_cache       > No debug file found for imu37nhqd4g.54eef5ce96cf37cb175b0d93186836ca1caf470c/executable (scope 554)
 DEBUG symbolicator::services::download                  > Fetched debug file from HTTP source 'imu37nhqd4g' location '54eef5ce96cf37cb175b0d93186836ca1caf470c/debuginfo'
 DEBUG symbolicator::services::download::sentry          > Fetching list of Sentry debug files from https://example.com/?debug_id=cef5ee54-cf96-cb37-175b-0d93186836ca&file_formats=uuidmap
 DEBUG reqwest::async_impl::client                       > response '200 OK' for https://example.com/?debug_id=cef5ee54-cf96-cb37-175b-0d93186836ca&file_formats=uuidmap
 DEBUG reqwest::async_impl::client                       > response '200 OK' for https://example.com/?debug_id=cef5ee54-cf96-cb37-175b-0d93186836ca&file_formats=uuidmap
 DEBUG reqwest::async_impl::client                       > response '200 OK' for https://example.com/?debug_id=cef5ee54-cf96-cb37-175b-0d93186836ca&file_formats=uuidmap
 DEBUG reqwest::async_impl::client                       > response '200 OK' for https://example.com/?debug_id=cef5ee54-cf96-cb37-175b-0d93186836ca&file_formats=uuidmap
 DEBUG symbolicator::services::download::sentry          > Fetching list of Sentry debug files from https://example.com/?debug_id=cef5ee54-cf96-cb37-175b-0d93186836ca&file_formats=sourcebundle&code_id=54eef5ce96cf37cb175b0d93186836ca1caf470c
 DEBUG reqwest::async_impl::client                       > response '200 OK' for https://example.com/?debug_id=cef5ee54-cf96-cb37-175b-0d93186836ca&file_formats=sourcebundle&code_id=54eef5ce96cf37cb175b0d93186836ca1caf470c
 DEBUG reqwest::async_impl::client                       > response '200 OK' for https://example.com/?debug_id=cef5ee54-cf96-cb37-175b-0d93186836ca&file_formats=sourcebundle&code_id=54eef5ce96cf37cb175b0d93186836ca1caf470c
 DEBUG reqwest::async_impl::client                       > response '200 OK' for https://example.com/?debug_id=cef5ee54-cf96-cb37-175b-0d93186836ca&file_formats=sourcebundle&code_id=54eef5ce96cf37cb175b0d93186836ca1caf470c
 DEBUG reqwest::async_impl::client                       > response '200 OK' for https://example.com/?debug_id=cef5ee54-cf96-cb37-175b-0d93186836ca&file_formats=sourcebundle&code_id=54eef5ce96cf37cb175b0d93186836ca1caf470c
 ERROR symbolicator::services::objects                   > Failed to fetch file list from sentry: failed to fetch data from Sentry
  caused by: failed sending request to Sentry
  caused by: error decoding response body: expected value at line 1 column 1
  caused by: expected value at line 1 column 1
```

I've tried to figure out how to make this work, but wasn't successful.

### PR DESCRIPTION
**Pull request by flub**
The bitcode service incorrectly errored out for errors from sources
instead of not providing a result.  This in turn results in any source
errors during bitcode lookups killing the entire symcache lookup, even
if no bitcode could be needed.

Fixes #640

#skip-changelog

### CODE REVIEW

File: crates/symbolicator/src/services/bitcode.rs [hunk 1]
```diff
@@ -229,17 +229,24 @@ impl BitcodeService {
...
         // First find the PList.
         let find_plist = self
             .fetch_file_from_all_sources(uuid, AuxDifKind::UuidMap, scope.clone(), sources.clone())
-            .await?;
+            .await;
         let plist_handle = match find_plist {
             Some(handle) => handle,
-            None => return Ok(None),
+            None => return None,
         };
```
Comment (loewenheim) [inline crates/symbolicator/src/services/bitcode.rs:240]: This looks like it could be `let plist_handle = find_plist?;`.

File: crates/symbolicator/src/services/bitcode.rs [hunk 2]
```diff
@@ -249,16 +256,16 @@ impl BitcodeService {
                 scope,
                 sources,
             )
-            .await?;
+            .await;
         let symbolmap_handle = match find_symbolmap {
             Some(handle) => handle,
-            None => return Ok(None),
+            None => return None,
```
Comment (loewenheim) [inline crates/symbolicator/src/services/bitcode.rs:262]: Same as above

File: crates/symbolicator/src/services/bitcode.rs (hunk 1 above)
Comment (flub) [reply crates/symbolicator/src/services/bitcode.rs]: totally, i'm surprised clippy didn't pick that up

**Review by loewenheim — APPROVED** [review]
