### PR TITLE
fix(proguard): Support Compose group-key mappings

### LINKED ISSUE #1065: Compose diagnostic stack traces not deobfuscated in Sentry
Jetpack Compose source-info stack traces (via `Composer.setDiagnosticStackTraceMode(ComposeStackTraceMode.Auto)`) are still obfuscated in Sentry for an app using Compose 1.10.1.

Customer reports they are on Sentry Gradle plugin 6.x, KGP 2.3.x, AGP 8.13.2, with `includeProguardMapping = true` and `autoUploadProguardMapping = true` (autoInstallation and tracingInstrumentation disabled).

Hypothesis: Compose mapping entries (e.g. `m$1349809332`) may be missing from the uploaded mapping because `merge{Variant}ComposeMapping` didn’t run, or `uploadSentryProguardMappings{Variant}` runs before `merge{Variant}ComposeMapping`.

Reference: [https://developer.android.com/develop/ui/compose/tooling/stacktraces](<https://developer.android.com/develop/ui/compose/tooling/stacktraces>)

### PR DESCRIPTION
**Pull request by romtsn**
Support Compose group-key mappings in symbolicator

Symbolicator caches ProGuard mappings through rust-proguard before JVM symbolication. `ComposeStackTrace` -> `$$compose` sections emitted by recent Android builds can use two-space member indentation, which caused older cached mappings to keep only the class-level remap and leave frames as `ComposeStackTrace.m$...` instead of resolving them to the original Compose methods.

This bumps proguard to 5.10.2, adds an integration test with a raw two-space `$$compose` mapping fixture, and bumps symbolicator's own ProGuard cache version so previously truncated caches are recomputed with the fixed parser.

Closes getsentry/sentry-android-gradle-plugin#1065

### CODE REVIEW

File: crates/symbolicator-service/src/caches/versions.rs [hunk 1]
```diff
@@ -283,6 +283,9 @@ pub const BUNDLE_INDEX_CACHE_VERSIONS: CacheVersions = CacheVersions {
 
 /// Proguard Cache, with the following versions:
 ///
+/// - `7`: Recompute caches after starting to support Compose
+///   mappings with two-space indentation.
```
Comment (loewenheim) [inline crates/symbolicator-service/src/caches/versions.rs]: I wouldn't put the "recompute" part in the docs.
```suggestion
/// - `7`: Caches now support Compose
///   mappings with two-space indentation.
```

File: crates/symbolicator-service/src/caches/versions.rs [hunk 2]
```diff
@@ -298,14 +301,15 @@ pub const BUNDLE_INDEX_CACHE_VERSIONS: CacheVersions = CacheVersions {
 ///
 /// - `1`: Initial version.
 pub const PROGUARD_CACHE_VERSIONS: CacheVersions = CacheVersions {
-    current: CacheVersion::new(6, CachePathFormat::V2),
+    current: CacheVersion::new(7, CachePathFormat::V2),
     fallbacks: &[],
```
Comment (loewenheim) [inline crates/symbolicator-service/src/caches/versions.rs]: I strongly suggest adding version 6 as a fallback here. Not having it means that all current caches are instantly invalidated and new ones need to be computed immediately. This isn't really necessary in this case—the old caches are still parseable. If you put the fallback, old caches will be reused until the new ones have been computed.

**Review by loewenheim — CHANGES_REQUESTED** [review]

File: crates/symbolicator-service/src/caches/versions.rs (hunk 2 above)
Comment (romtsn) [reply crates/symbolicator-service/src/caches/versions.rs]: TIL, thank you! added it

**Review by loewenheim — APPROVED** [review]

**Review by loewenheim — CHANGES_REQUESTED** [review]
Sorry, forgot: A changelog entry would be appreciated :)

**Review by loewenheim — APPROVED** [review]
