### PR TITLE
Fix symstore proxy path parsing

### LINKED ISSUE #1220: VS2022 paths are incorrectly parsed by proxy
Me again!

### Environment

Visual Studio 2022, Symbolicator 23.6.1 (and head). 

### Steps to Reproduce

1. Load minidump in Visual Studio 202
2. Add http://localhost:3021/proxy to the Symbol Paths
3. Run `symbolicator run -c config.yml`
4. Click "Load Symbols" in VS2022

### Expected Result

`parse_symstore_path` is called with "/Foo.pdb/ABCDEFG/Foo.pdb", and it parses `leading_fn`, `signature`, and `trailing_fn` to:
`Foo.pdb`, `ABCDEFG`, `Foo.pdb` respectively

### Actual Result

`parse_symstore_path` is called with "Foo.pdb/ABCDEFG/Foo.pdb". The code that splits this is
```
    let mut split = path.splitn(4, '/');
    // Skip the leading / that the path contains
    split.next()?;
    let leading_fn = split.next()?;
    let signature = split.next()?;
    let trailing_fn = split.next()?; <==== This errors
```

The first call to split.next is incorrect in this case, because the "path" doesn't begin with a /

### PR DESCRIPTION
**Pull request by Swatinem**
fixes #1220

#skip-changelog

### CODE REVIEW

File: crates/symbolicator-sources/src/paths.rs [hunk 1]
```diff
@@ -463,9 +463,7 @@ pub fn get_directory_paths(
 
 /// Parses a symstore path into a possible [`FileType`] and an [`ObjectId`].
 pub fn parse_symstore_path(path: &str) -> Option<(&'static [FileType], ObjectId)> {
-    let mut split = path.splitn(4, '/');
-    // Skip the leading / that the path contains
-    split.next()?;
+    let mut split = path.splitn(3, '/');
```
Comment (loewenheim) [inline crates/symbolicator-sources/src/paths.rs:466]: This assumes that the path _never_ starts with a `/`, right? Is that how it works in practice?

Comment (Swatinem) [reply crates/symbolicator-sources/src/paths.rs:466]: It is, yes.
All the testcases btw I took literally from https://github.com/dotnet/symstore/blob/main/docs/specs/SSQP_Key_Conventions.md

**Review by loewenheim — APPROVED** [review]
